spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/book-dev-db
    username: dev
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
